replicaCount: 3
image:
  repository: gaptraiing.azurecr.io/python-cicd
  tag: "6969b0ce76aed7b166eb39f0560a26ae8a023e84"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: acr-secret
service:
  type: ClusterIP
  port: 80
