replicaCount: 3
image:
  repository: gaptraiing.azurecr.io/python-cicd
  tag: "a5b35e4e45b4037542509ec91222962b4139b044"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: acr-secret
service:
  type: ClusterIP
  port: 3000
